### ISSUE TITLE
Show Tested in Patchwork series html listing

### ISSUE THREAD

**Issue by txsarvela** [dlespiau/patchwork#118]
Incoming Series html-page could have notification if there has been any (possibly automatical) testing done for the mbox, similar to the T-column in Incoming Patches -page.

This would give more visibility to the automatic testing and their results. It would also be easier to see at a glance, for example, authors whose patchsets systematically won't apply cleanly.

**Comment by dlespiau** [comment]
Yes, I do agree.

Belén (@belenbarrospena) had some resistance here because it was starting to be too many columns in the series page. Maybe we can convince her about that one last piece of information. If we want even  more columns, we'll have to start adding a mechanism to select which fields to display.

**Comment by belenbarrospena** [comment]
Right, this is your last column! ;) I'll add that in

**Comment by dlespiau** [comment]
So, it's a bit complicated, because that's the first time we have to really think about a plan to show data of the last revision at the series level. A rough plan to do that:
- Add a new field to the SeriesRevision that will hold a "total" test results for the series. Add the migration step (manage.py makemigrations). The reason to "cache" the aggregate test result in the revision object is [because of this](https://docs.djangoproject.com/en/1.8/topics/db/aggregation/#combining-multiple-aggregations/). That field can just be:
  
   test_state = models.SmallIntegerField(choices=TestResult.STATE_CHOICES)
- Every time a test result is posted on a series revision (we'll think about test results on patches later), Make sure we correctly set the SeriesRevision "total" test state. For instance if we have 2 tests on a revision, one is 'success', the other is 'warning', the total state for that revision is 'warning'. This is just the max for all results state, which can be queried with [aggregate](https://docs.djangoproject.com/en/1.8/topics/db/aggregation/#generating-aggregates-over-a-queryset) and the `Max` operator.
  
  This needs to be unit tested (test_series.py)
- Then, there's a long standing item: add a last_revision field to the Series object that is a foreign key to the last revision of a series. This is so getting the latest revision of the series become a simple `JOIN`. We can then get data stored on revisions at the series level quite easily. `test_state` is one of those.
  
  This also needs to be unit tested.
- We'll have to add the test_state in the data exposed in the series object of the REST API
- Add a columns in the series-list HTML page, using the same representation as the individual test results states

**Comment by dlespiau** [comment]
All in master and deployed on fdo!
