### ISSUE TITLE
500 error on series API access: KeyError: 'project_pk'

### ISSUE THREAD

**Issue by ruscur** [dlespiau/patchwork#131]
Internal Server Error: /api/1.0/projects/gfx/series/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 79, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 400, in dispatch
    response = handler(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/mixins.py", line 76, in list
    self.object_list = self.filter_queryset(self.get_queryset())
  File "/srv/patchwork/lib/apache2/../../patchwork/views/api.py", line 205, in get_queryset
    pk = self.kwargs['project_pk']
KeyError: 'project_pk'

When accessing the series page for a project, a request to a URL like /api/1.0/projects/gfx/series/ is made and returns 500 with the above message.  This must have something to do with the primary key in the database somewhere but I'm not really sure how to debug it, especially since project_pk isn't referenced anywhere else in the project.

**Comment by ruscur** [comment]
Tried a different database and now things work.  I think part of the cause is tables like patchwork_series not being included in the grant-all SQL scripts.

**Comment by dlespiau** [comment]
Hum, I don't think this has something to do with the database. The traceback is telling us that, for some reason, self.kwargs didn't contain the 'project_pk' key, that's something coming directly from the URL decoding and stored in the View objects by django rest framework.

In your case, '/api/1.0/projects/gfx/series/', kwargs['project_pk'] should contain 'gfx', which is then used to restrict the query to the series belonging to that project.

Now, the problem is, I have no idea why you encountered that error. It is quite puzzling. I wonder if it could have anything to do with a badly reloaded django and stopping/starting the server again would have solved it  (I have experienced the ./manage.py runserver HTTP server needing a full restart when switching between two branches with a large diff). If it's not too much trouble for you, could you try again  with the previous configuration to see if the error has "disappeared"?

**Comment by ruscur** [comment]
I may have also changed django versions...if it's not related to the database then I'll see if I can reproduce and figure out what environment change causes it.
