### ISSUE TITLE
link from git commit back to pw?

### ISSUE THREAD

**Issue by robclark** [dlespiau/patchwork#176]
(not so much a concrete feature request, but an interesting pie-in-the-sky idea I had the other day..)

I do use, for example, git/tig blame reasonably frequently to figure out why some code is the way it is.  But that only takes you back to individual commits and commit msgs.

But maybe if there was some meta-data that pw could stuff in the commit when it was pushed linking back to the pw series, then all of a sudden you have a link to the series cover-letter, and (I think?) previous revisions of the patchset, review comments, etc.  Which could all be quite interesting.

**Comment by dlespiau** [comment]
yes, that's absolutely something I had in mind as well. Right now there's a low-fi way to link to the patchwork patch from the msg id (so the link can be constructed with just the original email), see, for example, the Link tag in:

  https://cgit.freedesktop.org/drm-intel/commit/?id=9e60290dbafdf577766e5fc5f2fdb3be450cf9a6

Now, I also want to be able to have shorter links with the patch id. That needs cooperation from patchwork. The natural place is to add that link when downloading the mbox file from patchwork and adding the command line options to git-pw. A small wish list:
- no tag added by default
- I think I'd like to call the tag Patchwork: by default, so it's easy to parse from a commit
- Provide a way to override the tag name
- The link should be a link to the patch itself rather than the series I think. But then the patch page should have an easy way to navigate to the series (which it doesn't have right now, but that's on the plan)

**Comment by dlespiau** [comment]
Right, did something and that something is deploying on fdo. See https://github.com/dlespiau/patchwork/commit/2dc322d98cfdf210b8aa5e39825ce29777143e3a for the git-pw invocations (works with the apply, apply-patch, mbox and mbox-patch commands)
