### ISSUE TITLE
git-pw: RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by jviki** [dlespiau/patchwork#70]
Hello,

I downloaded the current master and trying to use the git-pw. I've configured git to test it as:

git config patchwork.default.url https://patchwork.freedesktop.org
git config patchwork.default.project intel-gfx

But anyway:

$ git-pw/git-pw
Traceback (most recent call last):
  File "git-pw/git-pw", line 347, in <module>
    parser.parse_args(namespace=git_pw.cmd)
  File "/usr/lib/python3.5/argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1747, in parse_known_args
    if not hasattr(namespace, action.dest):
  File "git-pw/git-pw", line 85, in **getattr**
    return self.meta[self.canonical_name()][name]
  File "git-pw/git-pw", line 88, in canonical_name
    if self.name in self.aliases:
  File "git-pw/git-pw", line 85, in **getattr**
[...]
  File "git-pw/git-pw", line 88, in canonical_name
    if self.name in self.aliases:
  File "git-pw/git-pw", line 85, in **getattr**
    return self.meta[self.canonical_name()][name]
  File "git-pw/git-pw", line 88, in canonical_name
    if self.name in self.aliases:
  File "git-pw/git-pw", line 85, in **getattr**
    return self.meta[self.canonical_name()][name]
  File "git-pw/git-pw", line 88, in canonical_name
    if self.name in self.aliases:
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by dlespiau** [comment]
oh, I think that's because your "python" is python 3, does specifying:

```
#!/usr/bin/env python2
```

solve the issue?

**Comment by jviki** [comment]
Yes, it works now! So treat it as a silly bug report ;), the code does not ask for python2 properly. Thank you.

**Comment by dlespiau** [comment]
Not silly at all! I didn't realize some distros would make python default to python3 (I'm surprised people would do that actually, it seems such a decision could break python2 scripts just asking for "python" because they were created before python 3 even existed). But anyway, pushed a fixed to master.

Thanks for the report.

**Comment by jviki** [comment]
True... Arch Linux did it quite a long time ago and it breaks a lot of things. By the way, is there some help, how to setup git-pw properly? I have no clue what URL to put there and what the "project" property is intended for. I wanted to try the git-pw for the http://dpdk.org/dev/patchwork and I didn't realize how to set it up.

**Comment by dlespiau** [comment]
Unfortunately, the patchwork on dpdk.org is quite old and not the branch in this git repo. The patchwork in this repository is only deployed on patchwork.freedesktop.org, because that's the only site I actually administrate myself.

There is some documentation on git-pw, but it won't be of any help for you, sorry :(

  http://patchwork-freedesktop.readthedocs.org/en/latest/manual.html#git-pw
